[build-system]
requires = [
    "setuptools>=61.0",
    "wheel",
    "setuptools_scm>=6.0",
    "tomli"
]

build-backend = "setuptools.build_meta"

[project]
dependencies = [
    "google-generativeai==0.4.1",
    "deepl==1.16.1",
    "openai==1.13.3",
    "backoff==2.2.1",
    "tiktoken==0.6.0"
]

name = "easytl"
version = "v0.0.4"
authors = [
  { name="Bikatr7", email="Tetralon07@gmail.com" },
]
description = "Wrapper for OpenAI, DeepL, and Gemini APIs for easy translation of text."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3.8",
    "License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/Bikatr7/EasyTL"
Issues = "https://github.com/Bikatr7/EasyTL/issues"
